# Generated by Django 3.1.2 on 2020-11-02 23:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seekers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seekers", "0026_auto_20201102_1800"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraCare",
            fields=[
                (
                    "human",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="seekers.human",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("complete", "Complete")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
            ],
            bases=(seekers.models.HumanMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ExtraCareNote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("note", ckeditor.fields.RichTextField()),
                (
                    "added_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("extracare", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinical.extracare")),
            ],
            options={"verbose_name": "Note", "ordering": ("-created",),},
        ),
        migrations.CreateModel(
            name="ExtraCareBenefitProxy",
            fields=[],
            options={"verbose_name": "Extra Care benefit report", "proxy": True, "indexes": [], "constraints": [],},
            bases=("clinical.extracare",),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("ALTER TABLE seekers_seekerbenefittype RENAME TO clinical_extracarebenefittype"),
                migrations.RunSQL("ALTER TABLE seekers_seekerbenefit RENAME TO clinical_extracarebenefit"),
                migrations.RunSQL(
                    "ALTER TABLE clinical_extracarebenefit ADD COLUMN extracare_id VARCHAR(4) REFERENCES clinical_extracare (human_id) ON DELETE CASCADE"
                ),
                migrations.RunSQL(
                    "INSERT INTO clinical_extracare (human_id, status) SELECT DISTINCT seeker_id AS human_id, 'inactive' as status FROM clinical_extracarebenefit"
                ),
                migrations.RunSQL("UPDATE clinical_extracarebenefit SET extracare_id = seeker_id"),
                migrations.RunSQL(
                    "ALTER TABLE clinical_extracarebenefit DROP COLUMN seeker_id, ALTER COLUMN extracare_id SET NOT NULL"
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ExtraCareBenefitType",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        ("name", models.CharField(max_length=120)),
                        ("default_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                    ],
                    options={"ordering": ("name",),},
                ),
                migrations.CreateModel(
                    name="ExtraCareBenefit",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        ("cost", models.DecimalField(decimal_places=2, max_digits=5)),
                        ("date", models.DateField()),
                        (
                            "benefit_type",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="clinical.extracarebenefittype"
                            ),
                        ),
                        (
                            "extracare",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinical.extracare"),
                        ),
                    ],
                    options={"ordering": ("-date",),},
                ),
            ],
        ),
    ]
