# Generated by Django 3.1.2 on 2020-11-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="extracare", options={"verbose_name": "Extra Care participant"},),
        migrations.AlterModelOptions(
            name="extracarebenefittype", options={"ordering": ("name",), "verbose_name": "Extra Care benefit type"},
        ),
        migrations.AddField(
            model_name="extracare", name="current_program_flow", field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ProgressEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_flow", models.PositiveIntegerField()),
                ("event_type", models.CharField(max_length=40)),
                ("scheduled", models.DateField(blank=True, null=True)),
                ("occurred", models.DateField(blank=True, null=True)),
                ("excused", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("complete", models.BooleanField(default=False, editable=False)),
                ("extracare", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clinical.extracare")),
            ],
            options={"ordering": ["id"],},
        ),
    ]
