# Generated by Django 3.1.2 on 2020-11-11 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_progressevent_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracarebenefit", name="cancelled", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extracarebenefit",
            name="rescheduled_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="extracarebenefit",
            name="scheduled",
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.RunSQL("UPDATE clinical_extracarebenefit SET scheduled = date"),
        migrations.AddField(
            model_name="progressevent",
            name="rescheduled_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="extracarebenefit", name="date", field=models.DateField(blank=True, null=True),
        ),
    ]
