# Generated by Django 3.1.2 on 2020-11-11 22:48

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_auto_20201111_1319"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionAgent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("point_of_contact", models.CharField(blank=True, max_length=120)),
                ("street_address", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(blank=True, max_length=30)),
                ("state", localflavor.us.models.USStateField(default="NC", max_length=2)),
                ("zip_code", localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        error_messages={"unique": "A person with this email is already in the system."},
                        max_length=254,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        error_messages={"unique": "A person with this phone number is already in the system."},
                        max_length=128,
                        region=None,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="extracarebenefittype",
            options={"ordering": ("connectionagent", "name"), "verbose_name": "Extra Care benefit type"},
        ),
        migrations.AddField(
            model_name="extracarebenefittype",
            name="connectionagent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="clinical.connectionagent"
            ),
        ),
    ]
