# Generated by Django 3.1.5 on 2021-01-10 01:59

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinical", "0005_auto_20201111_1748"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("c", "Create"), ("r", "Read"), ("u", "Update"), ("d", "Delete")], max_length=1
                    ),
                ),
                ("data", models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("extracare", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="clinical.extracare")),
                (
                    "object_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"], "index_together": {("object_ct", "object_id")},},
        ),
    ]
