# Generated by Django 2.1.7 on 2019-03-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20190307_2044"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendar", name="send_autotext_time",),
        migrations.AddField(
            model_name="calendar",
            name="autotext_days_in_advance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
