# Generated by Django 2.1.7 on 2019-03-21 22:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190317_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humancalendarsubscription',
            options={'verbose_name': 'Calendar subscription'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='send_autotext_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=13),
        ),
    ]
