# Generated by Django 2.2.14 on 2020-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20190321_1837"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="default_email_closing",
            field=models.TextField(
                blank=True, default="", help_text="Appended after autotext emails - break lines at 80 columns"
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="default_email_opening",
            field=models.TextField(
                blank=True, default="", help_text="Prepended to autotext emails - break lines at 80 columns"
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="default_sms_closing",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Appended after autotext SMS - be efficient with content - do not break lines unnecessarily",
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="default_sms_opening",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Prepended to autotext SMS - be efficient with content - do not break lines unnecessarily",
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="email_closing_override",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One-time override to email closing - reset after next autotext - break lines at 80 columns",
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="email_opening_override",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One-time override to email opening - reset after next autotext - break lines at 80 columns",
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="sms_closing_override",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One-time override to SMS closing - be efficient with content - do not break lines unnecessarily.",
            ),
        ),
        migrations.AddField(
            model_name="calendar",
            name="sms_opening_override",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One-time override to SMS opening - be efficient with content - do not break lines unnecessarily.",
            ),
        ),
    ]
