# Generated by Django 3.1.2 on 2020-10-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_auto_20200809_1947"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.CharField(max_length=120, primary_key=True, serialize=False)),
                ("summary", models.CharField(blank=True, default="", max_length=200)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("recurring_event_id", models.CharField(db_index=True, max_length=120, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("json", models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameField(
            model_name="humanattendance", old_name="recurring_event_id", new_name="legacy_recurring_event_id",
        ),
        migrations.AlterField(
            model_name="humanattendance",
            name="legacy_recurring_event_id",
            field=models.CharField(blank=True, db_column="recurring_event_id", db_index=True, max_length=120),
        ),
    ]
