# Generated by Django 3.1.2 on 2020-10-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_auto_20201016_0009"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="replies_go_to",
            field=models.CharField(
                choices=[("#general", "#general"), ("#techstuff", "#techstuff")], default="#rides", max_length=40
            ),
        ),
    ]
