# Generated by Django 3.1.2 on 2020-10-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_calendar_replies_go_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendar",
            options={"permissions": [("can_send_to_subscribers", "Can send messages to calendar subscribers")]},
        ),
    ]
