# Generated by Django 3.1.2 on 2021-01-09 22:15

from django.db import migrations, models


def save_all_attendance(apps, schema_editor):
    for attendance in apps.get_model("events", "HumanAttendance").objects.all():
        try:
            event = apps.get_model("events", "CalendarEvent").objects.get(id=attendance.event_id)
        except apps.get_model("events", "CalendarEvent").DoesNotExist:
            pass
        else:
            attendance.start_time = event.start_time
            attendance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_auto_20201029_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanattendance",
            name="start_time",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(save_all_attendance, lambda apps, schema_editor: None),
    ]
