# Generated by Django 2.1.7 on 2019-03-01 23:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', ckeditor.fields.RichTextField()),
                ('added_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='seeker',
            name='contact_preference',
            field=models.IntegerField(blank=True, choices=[(1, 'Email'), (2, 'SMS'), (3, 'Facebook')], null=True),
        ),
        migrations.AddField(
            model_name='seekernote',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekers.Seeker'),
        ),
    ]
