# Generated by Django 2.1.7 on 2019-03-26 15:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0006_auto_20190322_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPartner',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seekers.Human')),
                ('organization', models.CharField(blank=True, max_length=120)),
            ],
            bases=('seekers.human',),
        )
    ]
