# Generated by Django 2.1.7 on 2019-04-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0008_auto_20190327_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerbenefittype',
            name='default_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
