# Generated by Django 2.2.2 on 2019-06-25 21:49

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0009_auto_20190409_1924"),
    ]

    operations = [
        migrations.AddField(model_name="human", name="birthdate_x", field=models.DateField(blank=True, null=True),),
        migrations.AddField(
            model_name="human", name="sober_anniversary_x", field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="human", name="street_address_x", field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="human",
            name="zip_code_x",
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.RunSQL(
            (
                "UPDATE seekers_human SET birthdate_x = s.birthdate, sober_anniversary_x = s.sober_anniversary, "
                "street_address_x = s.street_address, zip_code_x = s.zip_code FROM seekers_seeker AS s WHERE "
                "id = s.human_ptr_id"
            ),
            (
                "UPDATE seekers_seeker SET birthdate = h.birthdate_x, sober_anniversary = h.sober_anniversary_x, "
                "street_address = h.street_address_x, zip_code = h.zip_code_x FROM seekers_human AS h WHERE "
                "human_ptr_id = h.id"
            ),
        ),
        migrations.RemoveField(model_name="seeker", name="birthdate",),
        migrations.RemoveField(model_name="seeker", name="sober_anniversary",),
        migrations.RemoveField(model_name="seeker", name="street_address",),
        migrations.RemoveField(model_name="seeker", name="zip_code",),
        migrations.RenameField(model_name="human", old_name="birthdate_x", new_name="birthdate"),
        migrations.RenameField(model_name="human", old_name="sober_anniversary_x", new_name="sober_anniversary",),
        migrations.RenameField(model_name="human", old_name="street_address_x", new_name="street_address",),
        migrations.RenameField(model_name="human", old_name="zip_code_x", new_name="zip_code",),
        migrations.AlterField(
            model_name="human",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "A person with this email is already in the system."},
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="human",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                error_messages={"unique": "A person with this phone number is already in the system."},
                max_length=128,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="seekerbenefit", name="cost", field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
