# Generated by Django 2.2.2 on 2019-06-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0012_seekerpairingmeeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="human", name="first_conversation", field=models.DateField(blank=True, null=True),
        ),
    ]
