# Generated by Django 2.2.2 on 2019-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0014_seeker_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='enroll_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
