# Generated by Django 2.2.14 on 2020-07-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0016_auto_20200703_1945"),
    ]

    operations = [
        migrations.AddField(model_name="seeker", name="donations_getter", field=models.BooleanField(default=False),),
        migrations.AddField(
            model_name="seeker",
            name="donor_thankyou_caller",
            field=models.BooleanField(default=False, verbose_name='Donor "Thank You" caller'),
        ),
        migrations.AddField(
            model_name="seeker",
            name="donor_thankyou_writer",
            field=models.BooleanField(default=False, verbose_name='Donor "Thank You" writer'),
        ),
        migrations.AddField(model_name="seeker", name="event_helper", field=models.BooleanField(default=False),),
        migrations.AddField(model_name="seeker", name="food_maker", field=models.BooleanField(default=False),),
        migrations.AddField(model_name="seeker", name="listening_line", field=models.BooleanField(default=False),),
        migrations.AddField(model_name="seeker", name="mediator", field=models.BooleanField(default=False),),
        migrations.AddField(
            model_name="seeker", name="one_on_one_facilitator", field=models.BooleanField(default=False),
        ),
        migrations.AddField(model_name="seeker", name="street_team", field=models.BooleanField(default=False),),
        migrations.AlterField(
            model_name="human",
            name="contact_preference",
            field=models.IntegerField(blank=True, choices=[(1, "Email"), (2, "SMS")], null=True),
        ),
        migrations.AlterField(
            model_name="seeker",
            name="activity_buddy",
            field=models.BooleanField(default=False, verbose_name="Connection Mission worthy"),
        ),
        migrations.AlterField(
            model_name="seeker",
            name="outreach",
            field=models.BooleanField(default=False, verbose_name="Listening Booth volunteer"),
        ),
        migrations.AlterField(
            model_name="seeker",
            name="space_holder",
            field=models.BooleanField(default=False, verbose_name="Space Owl"),
        ),
    ]
