# Generated by Django 2.2.14 on 2020-07-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0017_auto_20200703_2039"),
    ]

    operations = [
        migrations.AddField(
            model_name="human",
            name="send_replies_to_channel",
            field=models.CharField(blank=True, default="", editable=False, max_length=120),
        ),
    ]
