# Generated by Django 3.1.1 on 2020-09-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0019_auto_20200708_2317"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RenameField(model_name="communitypartner", old_name="human_ptr", new_name="human"),
                migrations.RenameField(model_name="seeker", old_name="human_ptr", new_name="human"),
            ],
            state_operations=[
                migrations.RemoveField(model_name="communitypartner", name="human_ptr",),
                migrations.RemoveField(model_name="seeker", name="human_ptr",),
                migrations.AddField(
                    model_name="communitypartner",
                    name="human",
                    field=models.OneToOneField(
                        default="abcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="seekers.human",
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="human",
                    field=models.OneToOneField(
                        default="abcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="seekers.human",
                    ),
                    preserve_default=False,
                ),
            ],
        )
    ]
