# Generated by Django 3.1.1 on 2020-09-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0019_auto_20200708_2317"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RenameField(model_name="communitypartner", old_name="human_ptr", new_name="human"),
                migrations.RenameField(model_name="seeker", old_name="human_ptr", new_name="human"),
            ],
            state_operations=[
                migrations.DeleteModel("seeker"),
                migrations.DeleteModel("communitypartner"),
                migrations.CreateModel(
                    name="Seeker",
                    fields=[
                        (
                            "human",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE, primary_key=True, to="seekers.Human",
                            ),
                        ),
                        ("birthdate", models.DateField(blank=True, null=True)),
                        ("sober_anniversary", models.DateField(blank=True, null=True)),
                        ("inactive_date", models.DateField(blank=True, null=True)),
                        ("facebook_username", models.CharField(blank=True, max_length=30)),
                        ("facebook_alias", models.CharField(blank=True, max_length=120)),
                        (
                            "listener_trained",
                            models.BooleanField(default=False, editable=False, verbose_name="Listener trained?"),
                        ),
                        (
                            "extra_care",
                            models.BooleanField(default=False, editable=False, verbose_name="Extra care program?"),
                        ),
                        (
                            "extra_care_graduate",
                            models.BooleanField(default=False, editable=False, verbose_name="Extra care graduate?"),
                        ),
                    ],
                    bases=(),
                ),
                migrations.CreateModel(
                    name="CommunityPartner",
                    fields=[
                        (
                            "human_ptr",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE, primary_key=True, to="seekers.Human",
                            ),
                        ),
                        ("organization", models.CharField(blank=True, max_length=120)),
                    ],
                    bases=(),
                ),
            ],
        )
    ]
