# Generated by Django 3.1.1 on 2020-09-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0020_auto_20200920_1542"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="human", options={"ordering": ["first_names", "last_names"], "verbose_name": "Human"},
        ),
        migrations.AddField(
            model_name="human", name="facebook_alias", field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="human", name="facebook_username", field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE seekers_human SET facebook_username = seekers_seeker.facebook_username, facebook_alias = seekers_seeker.facebook_alias FROM seekers_seeker WHERE seekers_seeker.human_id = seekers_human.id",
                    [],
                ),
            ],
            reverse_sql=[
                (
                    "UPDATE seekers_seeker SET facebook_username = seekers_human.facebook_username, facebook_alias = seekers_human.facebook_alias FROM seekers_human WHERE seekers_seeker.human_id = seekers_human.id",
                    [],
                ),
            ],
        ),
        migrations.RemoveField(model_name="seeker", name="facebook_alias",),
        migrations.RemoveField(model_name="seeker", name="facebook_username",),
    ]
