# Generated by Django 3.1.1 on 2020-10-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0021_auto_20200920_1820"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityPartnerService",
            fields=[
                ("service_code", models.CharField(max_length=15, primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="communitypartner",
            name="services",
            field=models.ManyToManyField(to="seekers.CommunityPartnerService"),
        ),
    ]
