# Generated by Django 3.1.1 on 2020-10-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0022_auto_20201004_2012"),
    ]

    operations = [
        migrations.AddField(model_name="seeker", name="herbal_first_aid", field=models.BooleanField(default=False),)
    ]
