# Generated by Django 3.1.2 on 2020-10-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0023_auto_20201004_2112"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name="communitypartner", name="human_ptr",),
                migrations.RemoveField(model_name="seeker", name="birthdate",),
                migrations.RemoveField(model_name="seeker", name="sober_anniversary",),
                migrations.AddField(
                    model_name="communitypartner",
                    name="human",
                    field=models.OneToOneField(
                        db_column="human_ptr_id",
                        default="abcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="seekers.human",
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="activity_buddy",
                    field=models.BooleanField(default=False, verbose_name="Connection Mission worthy"),
                ),
                migrations.AddField(
                    model_name="seeker", name="admin_human", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="connection_agent_organization",
                    field=models.CharField(blank=True, max_length=120),
                ),
                migrations.AddField(
                    model_name="seeker", name="creative_human", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker", name="donations_getter", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="donor_thankyou_caller",
                    field=models.BooleanField(default=False, verbose_name='Donor "Thank You" caller'),
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="donor_thankyou_writer",
                    field=models.BooleanField(default=False, verbose_name='Donor "Thank You" writer'),
                ),
                migrations.AddField(
                    model_name="seeker", name="enroll_date", field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="seeker", name="event_helper", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker", name="facilitator", field=models.BooleanField(default=False),
                ),
                migrations.AddField(model_name="seeker", name="food_maker", field=models.BooleanField(default=False),),
                migrations.AddField(
                    model_name="seeker", name="listening_line", field=models.BooleanField(default=False),
                ),
                migrations.AddField(model_name="seeker", name="mediator", field=models.BooleanField(default=False),),
                migrations.AddField(
                    model_name="seeker", name="needs_connection", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker", name="one_on_one_facilitator", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="outreach",
                    field=models.BooleanField(default=False, verbose_name="Listening Booth volunteer"),
                ),
                migrations.AddField(
                    model_name="seeker", name="ready_to_pair", field=models.BooleanField(default=False),
                ),
                migrations.AddField(model_name="seeker", name="ride_share", field=models.BooleanField(default=False),),
                migrations.AddField(
                    model_name="seeker",
                    name="seeker_pairings",
                    field=models.ManyToManyField(through="seekers.SeekerPairing", to="seekers.Seeker"),
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="space_holder",
                    field=models.BooleanField(default=False, verbose_name="Space Owl"),
                ),
                migrations.AddField(
                    model_name="seeker", name="street_team", field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name="seeker",
                    name="transportation",
                    field=models.IntegerField(
                        blank=True, choices=[(1, "Has a car"), (2, "Public transit/Lyft"), (3, "Homebound")], null=True
                    ),
                ),
                migrations.AlterField(
                    model_name="seeker",
                    name="extra_care",
                    field=models.BooleanField(default=False, editable=False, verbose_name="Extra care program"),
                ),
                migrations.AlterField(
                    model_name="seeker",
                    name="extra_care_graduate",
                    field=models.BooleanField(default=False, editable=False, verbose_name="Extra care graduate"),
                ),
                migrations.AlterField(
                    model_name="seeker",
                    name="human",
                    field=models.OneToOneField(
                        db_column="human_ptr_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="seekers.human",
                    ),
                ),
                migrations.AlterField(
                    model_name="seeker",
                    name="listener_trained",
                    field=models.BooleanField(default=False, editable=False, verbose_name="Listener trained"),
                ),
            ],
        )
    ]
