# Generated by Django 3.1.2 on 2020-10-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0024_auto_20201029_1535"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="human",
            options={
                "ordering": ["first_names", "last_names"],
                "permissions": [
                    ("can_send_masstext_to_one", "Can send individualized text/emails"),
                    ("can_send_masstext_to_several", "Can send text/emails to several humans at once"),
                    ("can_send_masstext_to_many", "Can send text/emails to lots of humans at once"),
                ],
                "verbose_name": "Human",
            },
        ),
    ]
