# Generated by Django 3.1.2 on 2020-11-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0025_auto_20201029_1538"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communitypartner", options={"ordering": ["human__first_names", "human__last_names"]},
        ),
        migrations.AlterModelOptions(
            name="seeker", options={"ordering": ["human__first_names", "human__last_names"]},
        ),
        migrations.AddField(
            model_name="seeker",
            name="lt_complete",
            field=models.DateField(blank=True, null=True, verbose_name="Completed Listening Training"),
        ),
        migrations.RunSQL(
            "UPDATE seekers_seeker SET lt_complete = seekers_seekermilestone.date FROM seekers_seekermilestone WHERE seekers_seekermilestone.milestone = 1 AND seekers_seeker.human_ptr_id = seekers_seekermilestone.seeker_id",
        ),
        migrations.RemoveField(model_name="seeker", name="listener_trained",),
        migrations.DeleteModel(name="SeekerBenefitProxy",),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name="seekerbenefit", name="benefit_type",),
                migrations.RemoveField(model_name="seekerbenefit", name="seeker",),
                migrations.DeleteModel(name="SeekerBenefit",),
                migrations.DeleteModel(name="SeekerBenefitType",),
            ],
        ),
    ]
