# Generated by Django 3.1.2 on 2020-11-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clinical", "0001_initial"), ("seekers", "0026_auto_20201102_1800")]

    operations = [
        migrations.RemoveField(model_name="seeker", name="extra_care",),
        migrations.RemoveField(model_name="seeker", name="extra_care_graduate",),
        migrations.DeleteModel(name="SeekerMilestone",),
    ]
