# Generated by Django 3.1.2 on 2020-11-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_auto_20201111_1748"),
        ("seekers", "0027_auto_20201102_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="seeker",
            name="connectionagent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="clinical.connectionagent"
            ),
        ),
        migrations.RunSQL(
            "INSERT INTO clinical_connectionagent (name, point_of_contact, street_address, city, state, zip_code, email, phone_number) SELECT DISTINCT connection_agent_organization, '', '', '', '' ,'' , '', '' FROM seekers_seeker ON CONFLICT DO NOTHING",
            "UPDATE seekers_seeker SET connection_agent_organization = clinical_connectionagent.name FROM clinical_connectionagent where seekers_seeker.connectionagent_id = clinical_connectionagent.id",
        ),
        migrations.RunSQL(
            "UPDATE seekers_seeker SET connectionagent_id = clinical_connectionagent.id FROM clinical_connectionagent WHERE seekers_seeker.connection_agent_organization = clinical_connectionagent.name",
            migrations.RunSQL.noop,
        ),
        migrations.RemoveField(model_name="seeker", name="connection_agent_organization",),
    ]
