# Generated by Django 3.1.2 on 2021-01-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seekers", "0026_auto_20201224_1524"),
        ("seekers", "0028_auto_20201111_1757"),
    ]

    operations = []
